setwd("E:\\R training Chennai\\Titanic")
train<-read.csv("train.csv", header= TRUE, sep = ",", na.strings = c(""))
test<-read.csv("test.csv", header= TRUE, sep = ",", na.strings = c(""))
str(train)
train$Survived<-as.factor(train$Survived)
train$Pclass<-as.factor(train$Pclass)
summary(train)
train$Age<-ifelse(is.na(train$Age), median(train$Age, na.rm=TRUE), train$Age)
is.character(train$Age)
sum(is.na(train$Age))
train$Embarked<-as.character(train$Embarked)
is.character(train$Embarked)
train$Embarked<-ifelse(is.na(train$Embarked), "S", train$Embarked)
sum(is.na(train$Embarked))
train$Embarked<-as.factor(train$Embarked)
is.factor(train$Embarked)
summary(train)
library(e1071)
skewness(train$Age)
skewness(train$Age)
boxplot(train$Age)
train$LN_Age <-log(train$Age)
train$LN_Fare <-log(train$Fare)
skewness(train$LN_Age)
skewness(train$LN_Fare)
train$LN_Fare<-ifelse(train$LN_Fare==-Inf, 0,train$LN_Fare)
library(MASS)
tbl<-table(train$Sex, train$Survived)
chisq.test(tbl)
tbl1<- table(train$Pclass, train$Survived)
chisq.test(tbl1)
tbl2<- table(train$Pclass, train$Sex)

tbl2<- table(train$Embarked, train$Survived)
chisq.test(tbl2)
library(Hmisc)
cormat= subset(train, select=c("Age", "SibSp", "Parch", "Fare"))
cormatrix<-rcorr(as.matrix(cormat))
cormat<-as.data.frame(cormatrix$r)


###################################################################
model<- glm(Survived~Pclass+Sex+Age+SibSp+Parch+Fare+Embarked, family = "binomial", data = train)
summary(model)

model_log<- glm(Survived~Pclass+Sex+Age+SibSp+Parch+LN_Fare+Embarked, family = "binomial", data = train)
summary(model_log)

train$probs <- model_log$fitted.values
train$preds_lr <- ifelse(train$probs>0.5,1,0)

cm_logreg <- table(train$Survived, train$preds_lr)
print(cm_logreg)


###################Test#################################################
setwd("E:\\R training Chennai\\Titanic")
summary(train)
test$Age<-ifelse(is.na(test$Age), median(test$Age, na.rm=TRUE), test$Age)
is.character(test$Age)
sum(is.na(test$Age))
test$Embarked<-as.character(test$Embarked)
is.character(test$Embarked)
test$Embarked<-ifelse(is.na(test$Embarked), "S", test$Embarked)
sum(is.na(train$Embarked))
test$Embarked<-as.factor(test$Embarked)
is.factor(test$Embarked)
summary(test)
library(e1071)
skewness(test$Age)
skewness(test$Age)
boxplot(test$Age)
test$LN_Age <-log(test$Age)
test$LN_Fare <-log(test$Fare)
skewness(test$LN_Age)
skewness(test$LN_Fare)
test$LN_Fare<-ifelse(test$LN_Fare==-Inf, 0,test$LN_Fare)
library(MASS)
tbl<-table(test$Sex, test$Survived)
chisq.test(tbl)
tbl1<- table(test$Pclass, test$Survived)
chisq.test(tbl1)
tbl2<- table(test$Pclass, test$Sex)

tbl2<- table(test$Embarked, test$Survived)
chisq.test(tbl2)
library(Hmisc)


cormat= subset(train, select=c("Age", "SibSp", "Parch", "Fare"))
cormatrix<-rcorr(as.matrix(cormat))
cormat<-as.data.frame(cormatrix$r)


